### ISSUE TITLE
Fortran code produces NaN output

### ISSUE THREAD

**Issue by traktofon** [johnfgibson/julia-pde-benchmark#4]
Testing with Nx=1024, this is the contents of `u.dat`:
```
  0.000000000000E+00                 NaN
                 NaN  0.196349540849E+00
                 NaN                 NaN
  0.392699081699E+00                 NaN
                 NaN  0.589048622548E+00
                 NaN                 NaN
...
```
First of all, the output formatting is wrong. As `u` is declared complex, the output format must account for three output items, i.e. change line 72 of `ksbenchmark.f90` to
```
write(10,'(3e20.12)') (x(i),u(i), i=0,Nx-1)
```
With this fixed, `u.dat` reads:
```
  0.000000000000E+00                 NaN                 NaN
  0.196349540849E+00                 NaN                 NaN
  0.392699081699E+00                 NaN                 NaN
...
```

Compiling with gfortran options `-ffpe-trap=invalid,zero,overflow` to catch the NaN creation, gdb points to line 129
```
uu = u_*u_
```
in iteration `n=2873`. Inspecting `u_` shows that many elements are larger than 1e180, which causes the overflow.

**Comment by johnfgibson** [comment]
I dug into the emergence of NaNs. It resulted from the lack of a reset to initial conditions (``u = u0``) between successive benchmarking runs of the integration code. Apparently when integrating over that laonger time interval (T=200 * 10 where 10 = Nruns), u(x,t) gets large and slopey enough to cause CFL problems for the given time step. 

Resetting the initial condition between each benchmark run produces the same u(x,T) as the other codes, up to eight or so digits. I put in some optional print statements of a norm on u(x,T) for verification of correctness. 

Also patched that ``write`` formatting error.

Thanks!
