### ISSUE TITLE
PDE benchmarks for Julia 1.x

### ISSUE THREAD

**Issue by KZiemian** [johnfgibson/julia-pde-benchmark#7]
I found this benchmarks extremely useful, when talking about Julia to physicists and I probably have one more talk in the future. As such I want to ask, if they will be updated to Julia 1.x? I don't know if there will be any difference in performance, just having results for current version is more convincing.

I was trying to make this code works in 1.x version, but this is still to advanced topic for me.

**Comment by johnfgibson** [comment]
Done (PR #8). The Julia naive and Julia unrolled algorithms are a little slower under julia-1.2.0 than julia-0.6.4, say 10% or 15%. But they're still compotetive with C, C++, Fortran.
